import nodemailer from "nodemailer";

interface EmailParams {
  to: string;
  recipientName: string;
  role: string;
  eventName: string;
  certificateId: string;
}

export async function sendCertificateEmail({ to, recipientName, role, eventName, certificateId }: EmailParams) {
  // Use environment variables or fallback to a test mock configuration for local development
  const transporter = nodemailer.createTransport({
    host: process.env.SMTP_HOST || "smtp.ethereal.email",
    port: parseInt(process.env.SMTP_PORT || "587"),
    auth: {
      user: process.env.SMTP_USER || "test_user",
      pass: process.env.SMTP_PASS || "test_pass",
    },
  });

  const validationUrl = `${process.env.NEXTAUTH_URL || "http://localhost:3000"}/validate/${certificateId}`;

  const htmlContent = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e5e7eb; border-radius: 8px; overflow: hidden;">
      <div style="background-color: #4f46e5; padding: 24px; text-align: center;">
        <h1 style="color: #ffffff; margin: 0; font-size: 24px;">Your Event Certificate is Ready!</h1>
      </div>
      <div style="padding: 32px; background-color: #ffffff;">
        <p style="font-size: 16px; color: #374151;">Hi <strong>${recipientName}</strong>,</p>
        <p style="font-size: 16px; color: #374151;">
          Congratulations! Your official digital certificate for <strong>${eventName}</strong> has been generated by the organizer.
        </p>
        <p style="font-size: 16px; color: #374151;">
          <strong>Role:</strong> ${role}
        </p>
        <div style="text-align: center; margin: 32px 0;">
          <a href="${validationUrl}" style="background-color: #4f46e5; color: #ffffff; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: bold; font-size: 16px; display: inline-block;">
            View and Download Certificate
          </a>
        </div>
        <p style="font-size: 14px; color: #6b7280; text-align: center;">
          Or copy and paste this secure validation link into your browser:<br>
          <a href="${validationUrl}" style="color: #4f46e5;">${validationUrl}</a>
        </p>
      </div>
      <div style="background-color: #f9fafb; padding: 16px; text-align: center; border-top: 1px solid #e5e7eb;">
        <p style="font-size: 12px; color: #9ca3af; margin: 0;">
          Powered by shim System<br>Cryptographically Secured
        </p>
      </div>
    </div>
  `;

  const mailOptions = {
    from: process.env.SMTP_FROM || '"shim Team" <noreply@shim.local>',
    to,
    subject: `Your Certificate for ${eventName}`,
    html: htmlContent,
  };

  try {
    // If SMTP_HOST is not provided, we just mock the email sending to the console.
    if (!process.env.SMTP_HOST) {
      console.log(`[MOCK EMAIL SENT TO ${to}]: View link -> ${validationUrl}`);
      return { success: true, message: "Mock email sent successfully" };
    }

    const info = await transporter.sendMail(mailOptions);
    console.log(`Email sent: ${info.messageId}`);
    return { success: true, messageId: info.messageId };
  } catch (error) {
    console.error("Error sending email:", error);
    return { success: false, error };
  }
}
